# Generated by Django 6.0.2 on 2026-02-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='fichiers',
            field=models.FileField(blank=True, null=True, upload_to='projet/fichiers/'),
        ),
        migrations.AddField(
            model_name='projet',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='projet/images/'),
        ),
    ]
