# Generated by Django 6.0.2 on 2026-03-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
