# Generated by Django 6.0.2 on 2026-03-12 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        ('tache', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tache.tache'),
        ),
    ]
