# Generated by Django 6.0.2 on 2026-02-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_limite', models.DateField()),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='a_faire', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
