# Generated by Django 6.0.2 on 2026-02-28 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipe', '0001_initial'),
        ('projet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='membres',
            field=models.ManyToManyField(related_name='equipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipe',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='projet.projet'),
        ),
    ]
